
export HYDRA_FULL_ERROR=1
export CUDA_VISIBLE_DEVICES=1,2

PYTHONUNBUFFERED=1 python3 -m verl.trainer.main_ppo \
 data.train_files=/home/wac/johnson/johnson/RLDecisionAgent/backend/GuessNumber/guess_data/train.parquet \
 data.val_files=/home/wac/johnson/johnson/RLDecisionAgent/backend/GuessNumber/guess_data/test.parquet \
 data.train_batch_size=16 \
 data.max_prompt_length=512 \
 data.max_response_length=256 \
 actor_rollout_ref.model.path=Qwen/Qwen2.5-0.5B-Instruct \
 actor_rollout_ref.actor.optim.lr=1e-6 \
 actor_rollout_ref.actor.ppo_mini_batch_size=4 \
 actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=4 \
 actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=8 \
 actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
 actor_rollout_ref.rollout.gpu_memory_utilization=0.4 \
 actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=4 \
 critic.optim.lr=1e-5 \
 critic.model.path=Qwen/Qwen2.5-0.5B-Instruct \
 critic.ppo_micro_batch_size_per_gpu=4 \
 algorithm.kl_ctrl.kl_coef=0.001 \
 trainer.logger=console \
 trainer.val_before_train=False \
 trainer.n_gpus_per_node=1 \
 trainer.nnodes=1 \
 trainer.save_freq=2 \
 trainer.test_freq=2 \
 trainer.total_epochs=10 2>&1 | tee guess_data_train.log